[package]
name = "advent_2018"
version = "0.1.0"
authors = ["jrheard <jrheard@cs.stanford.edu>"]
edition = "2018"

[dependencies]
chrono = "0.4"
hashbrown = "0.1"
itertools = "0.8"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_scan = "0.3.2"
rayon = "1.0"

[profile.dev]
opt-level = 3